### ISSUE TITLE
Upgrade Flot Charts

### ISSUE THREAD

**Issue by aalpern** [tessera-metrics/tessera#546]
Miraculously, the Flot charts project is under active development again! (see http://www.flotcharts.org/blog/2018/02/04/flot-216-new-maintainers/). Upgrade to the latest version. This will likely require a bunch of changes. 

* https://github.com/flot/flot
* https://www.flotcharts.org/
* https://www.npmjs.com/package/flot

Things that are likely to require changes:
* [x] Default time base of seconds, not millis: https://github.com/flot/flot/issues/1612. May need to add `timeBase: "milliseconds"`. See https://github.com/flot/flot/blame/master/CHANGELOG.md#L43
* [x] `autoscale` renamed to `autoScale`
* [x] various series options are now in a `series` sub-object. See https://github.com/flot/flot/blame/master/CHANGELOG.md#L20
  * [x] flot-barnumbers needs updating
* [x] the d3 stacking plugin no longer works - that will require some updating
* [x] time and axislabels plugins now baked-in
  * [x] converted tick formatter to a plugin
  * [ ] Could look at using the new `jquery.flot.absRelTime.js` plugin (more flexible time formatting), which allows for time format specification as well, which would handle #451
* ~~New logaxis plugin - does it change how log axes are specified?~~
* [x] Axis labels are messed up in tessera's charts
* [x] hover-over series highlighting causes weird rendering errors when axis labels are present
* [x] time series bar charts are rendering incorrectly
* [x] pie charts are not rendering at all
* [x] "- move backgroundColor and backgroundOpacity from legend settings to css" - might affect color themes
* [x] Update themes CSS to include axes, which are SVG now. https://github.com/flot/flot/blame/master/CHANGELOG.md#L76
* [x] Hover over is broken for pie charts (See https://github.com/flot/flot/issues/1645, currently in progress)
* [x] Hover over is broken for discrete bar charts
* [ ] Rendering error on horizontal discrete bar charts
* [x] Series highlighting doesn't work for time series bar charts, but I think that never worked
